# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 1
  - name: Experience
    url: experience/
    weight: 2
  - name: News
    url: news/
    weight: 3
  - name: Certificates
    url: certificates/
    weight: 4
  - name: Publications
    url: publications/
    weight: 11
  - name: Posts
    url: posts/
    weight: 25
  - name: Projects
    url: projects/
    weight: 30
  - name: Teaching
    url: teaching/
    weight: 40
